### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by hktr92** [ekino/phpstan-banned-code#37]
With PHP 8 around the corner, it would be nice to have support for it. Even if it's still in RC, I'm checking the compatibility of my project with this version.

**Comment by ovidals** [comment]
@hktr92 I'm working on it.

**Comment by nepda** [comment]
There is already a PR: https://github.com/ekino/phpstan-banned-code/pull/39

**Comment by cxlblm** [comment]
Hi @mremi , Is it possible to release a new version that supports php8?

**Comment by mremi** [comment]
Hi all, a new release is available https://github.com/ekino/phpstan-banned-code/releases/tag/v0.4.0
