### ISSUE TITLE
[Feature request] General setup to ban any statement

### ISSUE THREAD

**Issue by jasny** [ekino/phpstan-banned-code#5]
It would be nice if you'd be able to ban any type of statement/expression, similar to banning functions

```php
banned_code:
  statements:
    - echo
    - goto
    - exit
    - eval
  functions:
    - ...
```

**Comment by mremi** [comment]
Hi @jasny ,

I found a way to do that, but the config looks like:
```
parameters:
	banned_code:
		statements:
			- Stmt_Echo
			- Stmt_Goto
```

`Stmt_Echo` is the returned value of `Echo_::getType`.

`exit` and `eval` (and others) are expressions in `nikic/php-parser`, so maybe I should replace the node `functions` by `expressions` to be consistent.

WDYT?

**Comment by mremi** [comment]
Indeed, we can hide the difference between expressions and statements, but I would like to avoid maintaining a mapping with all of them, I mean:
```php
'Expr_Eval' => 'eval',
'Stmt_Echo' => 'echo',
'Stmt_Goto' => 'goto',
...
```
and let the developer configures the lib.

**Comment by jasny** [comment]
You don't have to maintain the mapping as you consistently convert the type `Expr_FooBar` becomes `foo_bar` and `Stmt_Rock` becomes `rock`.

**Comment by mremi** [comment]
Not sure about the benefit of this black magic because the developer has to do the conversion himself to configure the lib, and it can lead to errors, for instance `Stmt_TraitUseAdaptation_Precedence`.
