### ISSUE TITLE
Prevent baseline exclusion

### ISSUE THREAD

**Issue by Spomky** [ekino/phpstan-banned-code#65]
Hello,

`staab/phpstan-todo-by` allows to prevent errors from being present in the baseline (and [an option](https://github.com/staabm/phpstan-todo-by?tab=readme-ov-file#non-ignorable-errors) to disable this behavior).
This does not seem to be the case for this extension.

**❓ Question**: Is it possible to add this functionality here too?

Many thanks.
Kind regards.

**Comment by mremi** [comment]
Hi,

Good idea, do you think you can open a PR with this new feat?

Thanks

**Comment by mremi** [comment]
Handled in #66
